---
abstract: 'Create a nice formatted table using extended ASCII and ANSI colors'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::Exception: 0
  Test::More: 0.98
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-ANSITable
requires:
  Color::ANSI::Util: 0.03
  Data::Clone: 0
  Data::Unixish::Apply: 1.33
  Data::Unixish::ansi: 0.02
  DateTime: 0
  JSON: 0
  Log::Any: 0
  Module::List: 0
  Moo: 0
  Parse::VarName: 0
  SHARYANTO::Color::Util: 0
  Term::Detect: 0.02
  Term::Size: 0
  Text::ANSI::Util: 0.08
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Text-ANSITable
  repository: http://github.com/sharyanto/perl-Text-ANSITable
version: 0.12
